// Image-reading drills: questions generated by the simulator itself, answered from the echo image alone.
// Four kinds: which view is it, which structure is under the cross, which maneuver fixes the image, which
// setting improves it. Mistakes come back sooner (Leitner boxes kept in this browser).
import {VIEW_INFO,solveState,describeManeuver} from './views.mjs';
import {poseFromState,toWorld} from './geometry.mjs';
import {scanConvert} from './bmode.mjs';
import {LABEL,LABEL_NAMES} from './tissue.mjs';

const KEY='cardiolab.echo.drills.v1';
export const KINDS={view:'¿Qué vista es?',structure:'¿Qué estructura marca la cruz?',maneuver:'¿Qué maniobra la corrige?',knob:'¿Qué ajuste la mejora?'};
const KIND_SHORT={view:'Vistas',structure:'Estructuras',maneuver:'Maniobras',knob:'Ajustes'};
const PRESET_OF={plax:'plax',psax:'psax',apical:'apical',subcostal:'subcostal',ssn:'ssn'};
// views learners mistake for each other: preferred distractors
export const CONFUSED={plax:['a3c','psaxAV','a5c'],psaxAV:['psaxMV','scSAX','plax'],psaxMV:['psaxPM','psaxAV','a2c'],psaxPM:['psaxMV','a2c','sc4c'],a4c:['sc4c','a5c','a2c'],a5c:['a4c','a3c','plax'],a2c:['a4c','a3c','psaxPM'],a3c:['plax','a5c','a2c'],sc4c:['a4c','scSAX','a5c'],scSAX:['psaxAV','sc4c','ssn'],ssn:['scSAX','psaxAV','plax']};
export const STRUCTURES=[LABEL.LV_BLOOD,LABEL.RV_BLOOD,LABEL.LA_BLOOD,LABEL.RA_BLOOD,LABEL.AO_BLOOD,LABEL.PA_BLOOD,LABEL.LV_MYO,LABEL.RV_MYO,LABEL.LIVER];
// deliberately mis-set images; the student names the one control that fixes them
export const KNOBS=[
 {id:'gainLow',fix:'Sube la ganancia',params:{gain:.42},why:'Toda la imagen está oscura por igual, cerca y lejos: falta amplificación global.'},
 {id:'gainHigh',fix:'Baja la ganancia',params:{gain:2.3},why:'Las cavidades se llenan de ecos y los bordes pierden contraste en toda la imagen: sobra amplificación global.'},
 {id:'deep',fix:'Reduce la profundidad',depth:d=>Math.min(.24,d+.07),why:'El corazón queda pequeño en la parte alta del sector y sobra campo vacío: menos profundidad lo agranda y mejora la resolución temporal.'},
 {id:'shallow',fix:'Aumenta la profundidad',depth:d=>d*.55,why:'El sector corta las estructuras profundas: falta campo.'},
 {id:'farDark',fix:'Sube el TGC de las bandas lejanas',params:{tgc:[50,50,50,50,24,14,8,6]},why:'Solo el campo lejano está oscuro: se compensa por profundidad (TGC), no con la ganancia global, que saturaría el campo cercano.'},
 {id:'nearBright',fix:'Baja el TGC de las bandas cercanas',params:{tgc:[94,88,76,50,50,50,50,50]},why:'Solo el campo cercano está saturado: se corrige por profundidad (TGC); bajar la ganancia global oscurecería el resto.'}
];
const KNOB_VIEWS=['plax','psaxPM','a4c','sc4c'];
const MANEUVERS=[['rotation',[22,34]],['tilt',[10,15]],['rock',[10,15]],['z',[.018,.024]],['x',[.012,.018]]];

const pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const between=([a,b])=>a+Math.random()*(b-a),sign=()=>Math.random()<.5?-1:1;
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

// ---------------------------------------------------------------- spaced repetition (pure, testable)
const WEIGHT=[8,4,2,1,1];
export function itemWeight(item){return WEIGHT[Math.min(4,item?.box??0)]}
export function weightedPick(keys,items,rand=Math.random){const w=keys.map(k=>itemWeight(items[k])),total=w.reduce((a,b)=>a+b,0);let r=rand()*total;for(let i=0;i<keys.length;i++){r-=w[i];if(r<0)return keys[i]}return keys.at(-1)}
export function recordAnswer(stats,key,correct){const it=stats.items[key]||{box:0,seen:0,correct:0};it.seen++;if(correct){it.correct++;it.box=Math.min(4,it.box+1)}else it.box=0;it.last=Date.now();stats.items[key]=it;stats.answered++;if(correct)stats.correct++;return stats}
export function viewOptions(id,rand=Math.random){const others=Object.keys(VIEW_INFO).filter(v=>v!==id&&!(CONFUSED[id]||[]).includes(v));const d=[...(CONFUSED[id]||[])].filter(v=>VIEW_INFO[v]);while(d.length<3)d.push(others.splice(Math.floor(rand()*others.length),1)[0]);return shuffle([id,...d.slice(0,3)])}
// one-control misalignment from the ideal state; the answer undoes it
export function maneuverQuestion(ideal,[key,range],flip=sign()){const delta=flip*between(range),wrong={...ideal,[key]:ideal[key]+delta};
 const answer=describeManeuver(wrong,key,-delta),opposite=describeManeuver(wrong,key,delta);
 const others=shuffle(MANEUVERS.filter(m=>m[0]!==key)).slice(0,2).map(([k,r])=>describeManeuver(wrong,k,sign()*between(r)));
 const cap=s=>s.replace(/^./,c=>c.toUpperCase());return {wrong,key,delta,answer:cap(answer),options:shuffle([answer,opposite,...others].map(cap))}}

export function mountDrills(api){
 // api: {host, views, engine, apply(state,{animate}), setTgc(values), ySign(window), status(text), visible()}
 const host=api.host;let stats={answered:0,correct:0,items:{}};try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw?.items)stats={...stats,...raw}}catch{}
 const ideal=new Map();let q=null,token=0,answered=false;
 host.innerHTML=`<span class="eyebrow">LEER LA IMAGEN</span><h1>Reconoce sin ver el corazón</h1>
 <p class="lead">Preguntas creadas por el simulador: solo ves la imagen eco, como en el ecógrafo. Después de responder puedes abrir ese plano en el simulador, con el corazón visible, para entender la respuesta. Lo que fallas vuelve a salir antes.</p>
 <fieldset class="drill-kinds"><legend class="micro">Tipos de pregunta</legend>${Object.entries(KIND_SHORT).map(([k,v])=>`<label class="check"><input type="checkbox" value="${k}" checked> ${v}</label>`).join('')}</fieldset>
 <button id="drill-start" class="primary">Empezar</button>
 <section id="drill-card" class="drill-card" hidden>
  <p class="micro" id="drill-kind"></p><h2 id="drill-question"></h2>
  <figure class="drill-figure"><canvas id="drill-canvas" aria-label="Imagen eco de la pregunta"></canvas></figure>
  <figure class="drill-figure drill-target" id="drill-target-fig" hidden><canvas id="drill-target" aria-label="Imagen de la vista objetivo"></canvas><figcaption id="drill-target-cap"></figcaption></figure>
  <div id="drill-options" class="drill-options"></div>
  <div id="drill-feedback" class="drill-feedback" aria-live="polite"></div>
  <div id="drill-after" class="drill-after" hidden><button id="drill-open">Abrir en el simulador</button><button id="drill-next" class="primary">Siguiente →</button></div>
  <p class="micro">Teclas: 1–4 para responder · Intro para seguir.</p>
 </section>
 <section class="drill-stats"><h2>Tu progreso</h2><p id="drill-score" class="micro"></p><ul id="drill-by-kind" class="drill-by-kind"></ul><h3>Para repasar</h3><ul id="drill-weak" class="drill-weak"></ul><button id="drill-reset">Borrar progreso</button><p class="micro">Se guarda solo en este navegador · no acredita competencia clínica.</p></section>`;
 const $=id=>host.querySelector('#'+id);
 const kinds=()=>[...host.querySelectorAll('.drill-kinds input:checked')].map(i=>i.value);
 function save(){try{localStorage.setItem(KEY,JSON.stringify(stats))}catch{}renderStats()}
 function itemName(key){const [kind,id]=key.split(':');if(kind==='structure')return `Estructura · ${LABEL_NAMES[id]||id}`;if(kind==='knob')return `Ajuste · ${KNOBS.find(k=>k.id===id)?.fix||id}`;return `${KIND_SHORT[kind]} · ${VIEW_INFO[id]?.short||id}`}
 function renderStats(){
  $('drill-score').textContent=stats.answered?`${stats.correct} de ${stats.answered} respuestas correctas (${Math.round(100*stats.correct/stats.answered)} %)`:'Aún no has respondido ninguna pregunta.';
  const by={};for(const [k,it] of Object.entries(stats.items)){const kind=k.split(':')[0];by[kind]=by[kind]||{seen:0,correct:0};by[kind].seen+=it.seen;by[kind].correct+=it.correct}
  $('drill-by-kind').innerHTML=Object.entries(KIND_SHORT).filter(([k])=>by[k]).map(([k,v])=>`<li><span>${v}</span><b>${Math.round(100*by[k].correct/by[k].seen)} %</b><small>${by[k].seen}</small></li>`).join('');
  const weak=Object.entries(stats.items).filter(([,it])=>it.box===0&&it.seen>it.correct).sort((a,b)=>b[1].last-a[1].last).slice(0,5);
  $('drill-weak').innerHTML=weak.length?weak.map(([k])=>`<li>${esc(itemName(k))}</li>`).join(''):'<li class="empty">Nada pendiente.</li>';
 }
 function idealState(id){if(!ideal.has(id)){const t=api.views[id],sol=solveState(t,PRESET_OF[VIEW_INFO[id].window]);ideal.set(id,{...sol.state,depth:t.depth,sector:80,mode:'echo'})}return {...ideal.get(id)}}
 const jitter=(s,k=1)=>({...s,rotation:s.rotation+sign()*Math.random()*6*k,tilt:s.tilt+sign()*Math.random()*4*k,rock:s.rock+sign()*Math.random()*4*k});
 const standard={gain:1,tgc:Array(8).fill(50),freq:4,beating:false,lines:176};
 function render(frame,canvas,pose,ySign,cross){
  const ratio=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth||360,h=Math.round(w*.78);canvas.style.height=h+'px';canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);
  const g=canvas.getContext('2d'),scale=Math.min((w-16)/(2*pose.depth*Math.sin(pose.sector*Math.PI/360)),(h-14)/pose.depth),proj={cx:w/2,cy:ySign===1?7:h-7,scale,ySign};
  const img=g.createImageData(canvas.width,canvas.height);scanConvert(frame,img,proj,ratio);g.putImageData(img,0,0);g.setTransform(ratio,0,0,ratio,0,0);
  const a=pose.sector*Math.PI/360;g.fillStyle='#63ddc8';g.beginPath();g.arc(proj.cx+Math.sin(a)*16,proj.cy+ySign*Math.cos(a)*16,3,0,2*Math.PI);g.fill();
  if(cross){const x=proj.cx+cross[0]*scale,y=proj.cy+ySign*cross[1]*scale;g.strokeStyle='#ffe14d';g.lineWidth=2;g.beginPath();for(const [dx,dy] of [[-9,0],[9,0],[0,-9],[0,9]]){g.moveTo(x+dx*.35,y+dy*.35);g.lineTo(x+dx,y+dy)}g.stroke()}
 }
 function blank(canvas,text){const w=canvas.clientWidth||360,h=Math.round(w*.78);canvas.style.height=h+'px';canvas.width=w;canvas.height=h;const g=canvas.getContext('2d');g.fillStyle='#05080b';g.fillRect(0,0,w,h);g.fillStyle='#8aa1ae';g.font='12px Segoe UI';g.textAlign='center';g.fillText(text,w/2,h/2)}
 // ---------------------------------------------------------------- question builders
 async function buildView(){
  const id=weightedPick(Object.keys(VIEW_INFO),Object.fromEntries(Object.keys(VIEW_INFO).map(v=>[v,stats.items['view:'+v]])));const state=jitter(idealState(id));
  return {kind:'view',key:'view:'+id,state,window:VIEW_INFO[id].window,question:KINDS.view,options:viewOptions(id).map(v=>VIEW_INFO[v].name),answer:VIEW_INFO[id].name,
   why:`${VIEW_INFO[id].name}: ${VIEW_INFO[id].goal}`}
 }
 async function buildStructure(){
  for(let attempt=0;attempt<4;attempt++){
   const id=pick(Object.keys(VIEW_INFO)),state=jitter(idealState(id),.5),pose=poseFromState(state),half=pose.sector*Math.PI/360,cand=[],pts=[];
   for(let i=0;i<48;i++){const th=(Math.random()*2-1)*half*.8,r=pose.depth*(.15+Math.random()*.75),x=r*Math.sin(th),y=r*Math.cos(th);cand.push([x,y]);for(const [dx,dy] of [[0,0],[.003,0],[-.003,0],[0,.003],[0,-.003]])pts.push(toWorld(pose,x+dx,y+dy))}
   const labels=await api.engine.probe(pts),found=new Map();
   cand.forEach((c,i)=>{const l=labels.slice(i*5,i*5+5);if(l.every(v=>v===l[0])&&STRUCTURES.includes(l[0])&&!found.has(l[0]))found.set(l[0],c)});
   if(found.size<2)continue;
   const present=[...found.keys()],label=weightedPick(present.map(String),Object.fromEntries(present.map(l=>[l,stats.items['structure:'+l]])));const L=Number(label);
   const distract=shuffle(present.filter(l=>l!==L)).concat(shuffle(STRUCTURES.filter(l=>l!==L&&!present.includes(l)))).slice(0,3);
   return {kind:'structure',key:'structure:'+L,state,window:VIEW_INFO[id].window,cross:found.get(L),question:KINDS.structure,options:shuffle([L,...distract]).map(l=>LABEL_NAMES[l]),answer:LABEL_NAMES[L],
    why:`La cruz está en: ${LABEL_NAMES[L]}. Vista: ${VIEW_INFO[id].name}. Orienta primero la imagen (marcador, vértice) y después reconoce las cámaras por sus relaciones.`}
  }
  return buildView();
 }
 async function buildManeuver(){
  const id=weightedPick(Object.keys(VIEW_INFO),Object.fromEntries(Object.keys(VIEW_INFO).map(v=>[v,stats.items['maneuver:'+v]])));const base=idealState(id),m=maneuverQuestion(base,pick(MANEUVERS));
  return {kind:'maneuver',key:'maneuver:'+id,state:m.wrong,target:base,targetId:id,window:VIEW_INFO[id].window,question:`${KINDS.maneuver} Tu imagen (arriba) debería ser ${VIEW_INFO[id].short} (abajo).`,options:m.options,answer:m.answer,
   why:`${m.answer}. La imagen se desvió de ${VIEW_INFO[id].name} con un solo movimiento de la sonda; el contrario la devuelve. Ábrela en el simulador y pruébalo con el corazón visible.`}
 }
 async function buildKnob(){
  const kid=weightedPick(KNOBS.map(k=>k.id),Object.fromEntries(KNOBS.map(k=>[k.id,stats.items['knob:'+k.id]]))),k=KNOBS.find(x=>x.id===kid),id=pick(KNOB_VIEWS),state=idealState(id);
  if(k.depth)state.depth=k.depth(state.depth);if(k.params?.gain)state.gain=k.params.gain;
  const opposite={gainLow:'gainHigh',gainHigh:'gainLow',deep:'shallow',shallow:'deep',farDark:'nearBright',nearBright:'farDark'}[k.id];
  const others=shuffle(KNOBS.filter(x=>x.id!==k.id&&x.id!==opposite)).slice(0,2).map(x=>x.fix).concat(['Sube la frecuencia']);
  return {kind:'knob',key:'knob:'+k.id,knob:k,state,window:VIEW_INFO[id].window,params:k.params,question:KINDS.knob,options:shuffle([k.fix,KNOBS.find(x=>x.id===opposite).fix,...shuffle(others).slice(0,2)]),answer:k.fix,why:k.why}
 }
 const BUILD={view:buildView,structure:buildStructure,maneuver:buildManeuver,knob:buildKnob};
 async function next(){
  const enabled=kinds();if(!enabled.length){api.status('Elige al menos un tipo de pregunta');return}
  const my=++token;answered=false;$('drill-card').hidden=false;$('drill-after').hidden=true;$('drill-feedback').textContent='';$('drill-options').replaceChildren();$('drill-kind').textContent='';$('drill-question').textContent='Preparando la imagen…';
  $('drill-target-fig').hidden=true;blank($('drill-canvas'),'Simulando…');$('drill-card').scrollIntoView({block:'nearest',behavior:'smooth'});
  try{
   const built=await BUILD[pick(enabled)]();if(my!==token)return;q=built;
   const pose=poseFromState(q.state),ySign=api.ySign(q.window),frame=await api.engine.renderOnce(pose,{...standard,...(q.params||{})});if(my!==token)return;
   render(frame,$('drill-canvas'),pose,ySign,q.cross);
   if(q.target){const tp=poseFromState(q.target);$('drill-target-fig').hidden=false;$('drill-target-cap').textContent=`Objetivo: ${VIEW_INFO[q.targetId].name}`;blank($('drill-target'),'Simulando…');const tf=await api.engine.renderOnce(tp,standard);if(my!==token)return;render(tf,$('drill-target'),tp,ySign)}
   $('drill-kind').textContent=`${KIND_SHORT[q.kind]} · ${stats.items[q.key]?.seen?'repaso':'nueva'}`;$('drill-question').textContent=q.question;
   $('drill-options').replaceChildren(...q.options.map((text,i)=>{const b=document.createElement('button');b.innerHTML=`<kbd>${i+1}</kbd> ${esc(text)}`;b.dataset.text=text;b.onclick=()=>answer(text);return b}));
  }catch(e){if(my===token){$('drill-question').textContent='No se pudo generar la pregunta: '+e.message;$('drill-after').hidden=false}}
 }
 function answer(text){
  if(!q||answered)return;answered=true;const ok=text===q.answer;recordAnswer(stats,q.key,ok);save();
  for(const b of $('drill-options').children){b.disabled=true;b.classList.toggle('correct',b.dataset.text===q.answer);b.classList.toggle('wrong',!ok&&b.dataset.text===text)}
  $('drill-feedback').innerHTML=`<p class="${ok?'ok':'bad'}"><b>${ok?'Correcto':'No'}</b>${ok?'':` · era «${esc(q.answer)}»`}</p><p>${esc(q.why)}</p>`;
  $('drill-open').textContent=q.kind==='knob'?'Abrir mal ajustada y corregirla':'Abrir en el simulador';$('drill-after').hidden=false;$('drill-next').focus();
 }
 // the same plane in the main simulator, heart visible (for a settings question, with the setting still wrong)
 function open(){if(!q)return;api.apply({...q.state,mode:'echo'},{animate:false});
  if(q.kind==='knob'){api.setTgc?.(q.params?.tgc||Array(8).fill(50));api.status(`Imagen mal ajustada: ${q.answer.toLowerCase()} con la consola`)}else api.status('Plano de la pregunta abierto en el simulador')}
 $('drill-start').onclick=()=>{$('drill-start').textContent='Otra pregunta';next()};$('drill-next').onclick=next;$('drill-open').onclick=open;
 $('drill-reset').onclick=()=>{if(!confirm('¿Borrar tu progreso en las preguntas?'))return;stats={answered:0,correct:0,items:{}};save()};
 addEventListener('keydown',e=>{if(!api.visible()||e.ctrlKey||e.metaKey||e.altKey||e.target.closest?.('input,select,textarea'))return;
  if(q&&!answered&&/^[1-4]$/.test(e.key)){const b=$('drill-options').children[Number(e.key)-1];if(b){e.preventDefault();b.click()}}else if(answered&&e.key==='Enter'&&e.target.tagName!=='BUTTON'){e.preventDefault();next()}});
 renderStats();
 return {stop(){token++}};
}
