// Console inspired by the user's photograph. No manufacturer firmware or calibration.
export const initialDisplay=()=>({zoom:1,contrast:1,freq:4,tgc:Array(8).fill(50),measuring:false,points:[],measureKind:'',focus:.55,dr:52,thi:true,persistence:1});
export const PERSISTENCE=['Apagada','Baja','Media','Alta'];
export function tgcGain(values,depth){const f=Math.max(0,Math.min(1,depth))*(values.length-1),i=Math.floor(f),v=values[i]+((values[Math.min(i+1,values.length-1)]-values[i])*(f-i));return 2**((v-50)/25)}
export function distanceMM(a,b){return Math.hypot(b[0]-a[0],b[1]-a[1])*1000}
export function boundedCursor(x,y,pose){const theta=Math.max(-pose.sector*Math.PI/360,Math.min(pose.sector*Math.PI/360,Math.atan2(x,y))),r=Math.max(.002,Math.min(pose.depth,Math.hypot(x,y)));return [r*Math.sin(theta),r*Math.cos(theta)]}
export function applyDisplayTone(image,projection,ratio,pose,display){
 if(display.contrast===1&&display.tgc.every(v=>v===50))return;
 const curve=Array.from({length:256},(_,v)=>255*(v/255)**display.contrast),gains=Array.from({length:256},(_,v)=>tgcGain(display.tgc,v/255)),a=image.data;
 for(let py=0;py<image.height;py++){const y=(py/ratio-projection.cy)/(projection.scale*projection.ySign);if(y<0)continue;for(let px=0;px<image.width;px++){
  const x=(px/ratio-projection.cx)/projection.scale,depth=Math.hypot(x,y)/pose.depth;if(depth>1||(depth>0&&Math.abs(Math.atan2(x,y))>pose.sector*Math.PI/360))continue;
  const i=(py*image.width+px)*4,g=gains[Math.min(255,Math.round(depth*255))];for(let c=0;c<3;c++)a[i+c]=Math.min(255,curve[a[i+c]]*g);
 }}
}

const KNOBS=[
 {key:'gain',name:'Ganancia 2D',min:.3,max:2.5,step:.1,unit:'×',format:v=>v.toFixed(1),hint:'Amplifica toda la señal recibida, también el ruido. Una ganancia alta «llena» de ecos las cavidades.'},
 {key:'depth',name:'Profundidad',min:3,max:24,step:.5,unit:'cm',factor:100,format:v=>v.toFixed(1),hint:'Modifica la extensión del sector. Observa qué estructuras quedan incluidas.'},
 {key:'sector',name:'Sector',min:45,max:110,step:1,unit:'°',format:v=>v.toFixed(0),hint:'Abre o estrecha el campo de exploración.'},
 {key:'freq',name:'Frecuencia',min:2,max:12,step:.5,unit:'MHz',format:v=>v.toFixed(1),hint:'Más frecuencia: mejor resolución y speckle más fino, pero menos penetración. Pruébalo en el campo lejano.'},
 {key:'focus',name:'Foco',min:1,max:24,step:.5,unit:'cm',format:v=>v.toFixed(1),read:s=>s.display.focus*s.state.depth*100,write:(v,s)=>Math.max(.1,Math.min(.95,v/100/s.state.depth)),hint:'Profundidad del foco de transmisión (triángulo en la escala). Ahí el haz es más estrecho: colócalo a la altura de lo que estudias.'},
 {key:'dr',name:'Rango dinám.',min:30,max:80,step:2,unit:'dB',format:v=>v.toFixed(0),hint:'Compresión: poco rango da una imagen contrastada (blanco y negro); mucho rango, más grises y más ruido visible.'},
 {key:'zoom',name:'Zoom',min:1,max:2.5,step:.1,unit:'×',format:v=>v.toFixed(1),hint:'Amplía la presentación alrededor del centro del sector; no cambia la posición de la sonda.'},
 {key:'contrast',name:'Contraste',min:.5,max:2,step:.1,unit:'×',format:v=>v.toFixed(1),hint:'Modifica los tonos de la imagen eco. Escala visual, no rango dinámico calibrado en dB.'}
];

export function mountInstrument(api){
 const $=id=>document.getElementById(id),host=$('instrument'),knobs=[],tgc=[];let opened=true;
 host.innerHTML=`<div class="console-title"><div><span class="console-led"></span><strong>Consola de práctica</strong></div><button id="console-collapse" aria-expanded="true" aria-controls="console-body">Ocultar consola</button></div>
 <div id="console-body"><div class="console-knobs" id="console-knobs"></div><div class="console-deck">
 <section class="tgc-bank"><div class="panel-caption">TGC <span>Compensación por profundidad</span></div><div class="tgc-ends"><span>Cerca</span><span>− brillo +</span></div><div id="tgc-sliders"></div><div class="tgc-ends"><span>Lejos</span><button id="tgc-reset">Centrar TGC</button></div></section>
 <section class="mode-bank"><div class="panel-caption">Modos</div><div class="mode-keys"><button id="console-2d" class="machine-key lit">2D</button><button id="console-anatomy" class="machine-key">Anatomía</button><button data-console-mode="M" class="machine-key theory">M<small>Concepto</small></button><button id="console-color" class="machine-key">Color<small>Doppler</small></button><button id="console-pw" class="machine-key">PW<small>Pulsado</small></button><button id="console-cw" class="machine-key">CW<small>Continuo</small></button><button id="console-thi" class="machine-key">THI<small>Armónico</small></button><button id="console-persist" class="machine-key">Persist.<small id="console-persist-level">Baja</small></button></div><button id="console-auto" class="machine-key">Restablecer imagen</button><p class="panel-small">Vuelve a valores de partida.</p></section>
 <section class="track-bank"><div class="track-keys"><button id="console-cursor" class="machine-key">Cursor</button><button id="console-caliper" class="machine-key">Cáliper</button></div><div id="console-trackball" class="trackball" tabindex="0" role="group" aria-label="Esfera de control del cursor: arrastra o usa las flechas"><span></span></div><div class="track-keys"><button id="console-set" class="machine-key">Fijar punto</button><button id="console-clear" class="machine-key">Borrar</button></div><label class="panel-small measure-kind">Medida <select id="console-measure-kind" aria-label="Qué mide el cáliper"><option value="">Distancia libre</option></select></label><p id="console-measurement" class="panel-small" aria-live="polite">Arrastra la esfera para mover el cursor sobre el corte.</p></section>
 <section class="capture-bank"><div class="panel-caption">Adquisición</div><button id="console-freeze" class="machine-key wide">Congelar</button><button id="console-capture" class="machine-key wide">Archivar captura</button><button id="console-record" class="machine-key wide">Grabar 10 s</button><button id="console-help" class="machine-key wide">Ayuda de controles</button></section>
 </div><div class="console-feedback"><span id="console-hint" role="status">Perillas: arrastra arriba/abajo, usa la rueda o las flechas del teclado.</span><span id="console-state">Preparando imagen…</span></div></div>`;
 function hint(text){$('console-hint').textContent=text}
 for(const k of KNOBS){
  const unit=document.createElement('div');unit.className='knob-unit';const label=document.createElement('label');label.textContent=k.name;label.htmlFor=`knob-${k.key}`;
  const knob=document.createElement('div');knob.id=`knob-${k.key}`;knob.className='knob';knob.tabIndex=0;knob.setAttribute('role','slider');knob.setAttribute('aria-label',k.name);knob.setAttribute('aria-valuemin',k.min);knob.setAttribute('aria-valuemax',k.max);knob.setAttribute('aria-orientation','vertical');knob.innerHTML='<i></i>';
  const line=document.createElement('div');line.className='knob-value';const number=document.createElement('input');number.type='number';number.min=k.min;number.max=k.max;number.step=k.step;number.id=`console-value-${k.key}`;number.setAttribute('aria-label',`${k.name} de consola`);const suffix=document.createElement('span');suffix.textContent=k.unit;line.append(number,suffix);unit.append(label,knob,line);$('console-knobs').append(unit);
  const value=()=>{const s=api.snapshot();return k.read?k.read(s):(s.display[k.key]??s.state[k.key])*(k.factor||1)};
  const blocked=()=>{const s=api.snapshot();return !s.ready||(s.realEcho&&['depth','sector','freq'].includes(k.key))||(s.frozen&&['gain','depth','sector'].includes(k.key)&&!(s.realEcho&&k.key==='gain'))};
  const set=v=>{if(blocked()||!Number.isFinite(v))return;v=Number(Math.max(k.min,Math.min(k.max,Math.round(v/k.step)*k.step)).toFixed(5));api.set(k.key,k.write?k.write(v,api.snapshot()):v/(k.factor||1));hint(k.hint);update()};
  number.onchange=()=>set(Number(number.value));knob.onfocus=()=>hint(k.hint);knob.onkeydown=e=>{const d={ArrowUp:1,ArrowRight:1,ArrowDown:-1,ArrowLeft:-1,PageUp:5,PageDown:-5}[e.key];if(d){e.preventDefault();set(value()+d*k.step)}else if(e.key==='Home'||e.key==='End'){e.preventDefault();set(e.key==='Home'?k.min:k.max)}};
  knob.addEventListener('wheel',e=>{e.preventDefault();set(value()+(e.deltaY<0?1:-1)*k.step)},{passive:false});
  let drag=null;knob.onpointerdown=e=>{if(e.button!==0||blocked())return;e.preventDefault();knob.focus();drag={y:e.clientY,value:value()};knob.setPointerCapture(e.pointerId)};knob.onpointermove=e=>{if(drag)set(drag.value+(drag.y-e.clientY)/7*k.step)};for(const name of ['pointerup','pointercancel','lostpointercapture'])knob.addEventListener(name,()=>drag=null);
  knobs.push({k,knob,number,value,blocked});
 }
 for(let i=0;i<8;i++){const label=document.createElement('label');label.className='tgc-row';const text=document.createElement('span');text.textContent=i+1;const input=document.createElement('input');input.type='range';input.min=0;input.max=100;input.step=1;input.value=50;input.id=`tgc-${i}`;input.setAttribute('aria-label',`TGC banda ${i+1} de cerca a lejos`);input.oninput=()=>{api.tgc(i,Number(input.value));hint(`TGC ${i+1}: modifica el brillo de esa profundidad en la imagen eco; sobre vídeo, por bandas de imagen.`);update()};label.append(text,input);$('tgc-sliders').append(label);tgc.push(input)}
 let ball=null;const track=$('console-trackball');track.onpointerdown=e=>{if(e.button!==0||!api.snapshot().ready||api.snapshot().realEcho)return;e.preventDefault();track.focus();ball=[e.clientX,e.clientY];track.setPointerCapture(e.pointerId);api.cursor(0,0)};track.onpointermove=e=>{if(!ball)return;api.cursor(e.clientX-ball[0],e.clientY-ball[1]);ball=[e.clientX,e.clientY];hint('El cursor sigue el plano mostrado. Activa Cáliper y fija dos puntos para una distancia del atlas.');update()};for(const n of ['pointerup','pointercancel','lostpointercapture'])track.addEventListener(n,()=>ball=null);
 track.onkeydown=e=>{const delta={ArrowLeft:[-3,0],ArrowRight:[3,0],ArrowUp:[0,-3],ArrowDown:[0,3]}[e.key];if(delta){e.preventDefault();api.cursor(...delta);update()}};
 $('console-collapse').onclick=()=>{opened=!opened;$('console-body').hidden=!opened;$('console-collapse').textContent=opened?'Ocultar consola':'Mostrar consola';$('console-collapse').setAttribute('aria-expanded',String(opened))};
 $('console-2d').onclick=()=>api.mode('echo');$('console-anatomy').onclick=()=>api.mode('anatomy');document.querySelectorAll('[data-console-mode]').forEach(b=>b.onclick=()=>api.explain(b.dataset.consoleMode));$('console-pw').onclick=()=>{api.dopplerMode?.('pw');hint('PW: pulsa la imagen para colocar el volumen de muestra. Pulsa el espectro para medir una velocidad.');update()};$('console-cw').onclick=()=>{api.dopplerMode?.('cw');hint('CW: pulsa la imagen para orientar la línea. Alinéala con el jet: ΔP = 4·v².');update()};$('console-color').onclick=()=>{api.colorToggle?.();hint('Doppler color: rojo = hacia el transductor, azul = alejándose. Pulsa la imagen para mover la caja; la escala fija el límite de Nyquist.');update()};
 $('console-cursor').onclick=()=>{api.measure(false);api.cursor(0,0);update()};$('console-caliper').onclick=()=>{api.measure(!api.snapshot().display.measuring);hint('Fija dos puntos con la esfera o pulsa directamente el corte. Distancia del atlas, no del paciente.');update()};$('console-set').onclick=()=>{api.fixPoint();update()};$('console-clear').onclick=()=>{api.clear();update()};
 $('tgc-reset').onclick=()=>{for(let i=0;i<8;i++)api.tgc(i,50);hint('TGC centrado.');update()};$('console-auto').onclick=()=>{api.reset();hint('Valores docentes restablecidos. Se conserva la posición de la sonda.');update()};
 for(const [target,source] of [['console-freeze','freeze'],['console-capture','capture'],['console-record','record']])$(target).onclick=()=>{$(source).click();update()};$('console-help').onclick=()=>api.explain('controls');
 $('console-thi').onclick=()=>{api.set('thi',!api.snapshot().display.thi);hint('Armónico (THI): la imagen se forma al doble de frecuencia. Menos ruido cercano y lóbulos laterales, bordes más nítidos; algo menos de penetración. Apágalo para comparar con el fundamental.');update()};
 $('console-persist').onclick=()=>{api.set('persistence',(api.snapshot().display.persistence+1)%PERSISTENCE.length);hint('Persistencia: promedia cuadros sucesivos. Suaviza el speckle pero emborrona lo que se mueve rápido (válvulas).');update()};
 const kind=$('console-measure-kind');for(const [k,name] of api.measureKinds||[]){const o=document.createElement('option');o.value=k;o.textContent=name;kind.append(o)}kind.onchange=()=>{api.measureKind?.(kind.value);hint('Nombra lo que mides para ver su puntuación Z según la superficie corporal del paciente. Coloca el cáliper como indica la referencia.');update()};
 function update(){const s=api.snapshot();for(const item of knobs){const v=item.value(),disabled=item.blocked();item.knob.style.setProperty('--turn',`${-135+270*(v-item.k.min)/(item.k.max-item.k.min)}deg`);item.knob.setAttribute('aria-valuenow',String(Number(v.toFixed(2))));item.knob.setAttribute('aria-valuetext',`${item.k.format(v)} ${item.k.unit}`);item.knob.setAttribute('aria-disabled',String(disabled));item.number.disabled=disabled;if(document.activeElement!==item.number)item.number.value=item.k.format(v)}tgc.forEach((input,i)=>{input.value=s.display.tgc[i];input.disabled=!s.ready});
  $('console-freeze').textContent=s.frozen?'Reanudar':'Congelar';$('console-freeze').classList.toggle('lit',s.frozen);$('console-record').textContent=s.recording?'Detener grabación':'Grabar 10 s';$('console-record').classList.toggle('lit',s.recording);$('console-2d').classList.toggle('lit',s.state.mode==='echo');$('console-anatomy').classList.toggle('lit',s.state.mode==='anatomy');$('console-caliper').classList.toggle('lit',s.display.measuring);$('console-color').classList.toggle('lit',!!s.color);$('console-thi').classList.toggle('lit',!!s.display.thi);$('console-persist-level').textContent=PERSISTENCE[s.display.persistence];$('console-thi').disabled=$('console-persist').disabled=!s.ready||!s.sim;$('console-pw').classList.toggle('lit',s.dop==='pw');$('console-cw').classList.toggle('lit',s.dop==='cw');$('console-pw').disabled=$('console-cw').disabled=!s.ready||!(s.sim||s.state.mode==='anatomy');$('console-color').disabled=!s.ready||!s.sim;
  for(const id of ['console-freeze','console-capture','console-record','console-cursor','console-caliper','console-clear','console-auto'])$(id).disabled=!s.ready;
  $('console-record').disabled=!s.ready||$('record').disabled;$('console-set').disabled=!s.ready||!s.display.measuring;$('console-auto').disabled=!s.ready||s.frozen;$('console-2d').disabled=!s.ready||s.frozen;$('console-anatomy').disabled=!s.ready||s.frozen||!!s.imageOnly;
  for(const id of ['console-cursor','console-caliper','console-set'])if(s.realEcho)$(id).disabled=true;track.setAttribute('aria-disabled',String(s.realEcho||!s.ready));
  $('console-state').textContent=s.realEcho?(s.frozen?'Vídeo congelado':'Clip real · procesamiento de imagen'):s.state.mode==='anatomy'?'Anatomía del atlas':s.frozen?'Congelado':s.sim?`2D simulado · ${s.display.freq.toFixed(1)} MHz`:'2D · contornos del atlas';
  const points=s.display.points;kind.value=s.display.measureKind||'';kind.disabled=!s.ready||s.realEcho;$('console-measurement').textContent=s.realEcho?'Cáliper del atlas no disponible sobre el clip: falta calibración y registro al paciente.':points.length===2?`${api.caliperText?.()} · anatomía de referencia escalada, no una medida clínica`:s.display.measuring?`${points.length} / 2 puntos · pulsa el corte o usa Fijar punto`:'Arrastra la esfera o usa las flechas para mover el cursor.';
 }
 update();return {update};
}
